name: Build SEA

on:
  push:
    branches: [ "main" ]
    paths: 'src/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'development'
jobs:
    deploy:
      runs-on: ${{ matrix.runner }}
      strategy:
        fail-fast: false
        matrix:
          include:
          - runner: self-hosted
            labels: Linux
            arch: ARM64
          #- runner: self-hosted
          #  labels: macOS
          #  arch: ARM64
          - runner: ubuntu-latest
            labels: Linux
            arch: x86_64
          - runner: windows-latest
      steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v4
    
        - name: Setup Node.js
          id: setup-node
          uses: actions/setup-node@v4
          with:
            node-version: 21.7.0
    
        - name: Find Node
          id: find-node
          run: |
            if [[ "${{ matrix.runner }}" == "windows-latest" ]]; then
              where node
            else
              #echo "node=$(which node)" >> "$GitHub_OUTPUT"
              which node
              whereis node
            fi
        - name: SEA
          id: sea
          uses: bryopsida/node-sea-action@v1
          with:
            working-dir: .
            output-dir: build
            executable-name: sea
            sea-config-path: sea-config.json
            node-path: /opt/hostedtoolcache/node/21.7.0/x64/bin/node
    
        - uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.runner }}-sea
            path: build/
            if-no-files-found: error
