name: Build SEA

on:
  push:
    branches: [ "main" ]
    paths: 'src/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'development'
jobs:
    deploy:
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, windows-latest] #, macos-latest
          arch: [x64, arm64]
      steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v4
    
        - name: Setup Node.js
          id: setup-node
          uses: actions/setup-node@v4
          with:
            node-version: 21.7.0
        - name: Find Node (UNIX)
          id: find-node-unix
          if: runner.os == 'Linux'
          run: |
            #echo "node=$(which node)" >> "$GitHub_OUTPUT"
            which node
            whereis node
        - name: Find Node (Windows)
          id: find-node-windows
          if: runner.os == 'Windows'
          run: |
            (Get-Command node).Source
        - name: SEA (Unix)
          id: sea-unix
          if: runner.os != 'Windows'
          uses: bryopsida/node-sea-action@v1
          with:
            working-dir: .
            output-dir: build
            executable-name: sea
            sea-config-path: sea-config.json
            node-path: /opt/hostedtoolcache/node/21.7.0/x64/bin/node
            
        - name: SEA (Windows)
          id: sea-windows
          if: runner.os == 'Windows'
          uses: bryopsida/node-sea-action@v1
          with:
            working-dir: .
            output-dir: build
            executable-name: sea
            sea-config-path: sea-config.json
            node-path: C:\hostedtoolcache\windows\node\21.7.0\x64\node.exe
    
        - uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.os }}-${{ matrix.arch }}-sea
            path: build/
            if-no-files-found: error
