name: Build SEA

on:
  push:
    branches: [ "main" ]
    paths: 'src/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'development'
jobs:
    deploy:
      strategy:
        matrix:
          os: [ubuntu-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout
          id: checkout
          uses: actions/checkout@v4
    
        - name: Setup Node.js
          id: setup-node
          uses: actions/setup-node@v4
          with:
            node-version: 21.7.0
    
        - name: Find Node
          id: find-node
          run: |
            #echo "node=$(which node)" >> "$GitHub_OUTPUT"
            which node
            whereis node
        - name: SEA
          id: sea
          uses: bryopsida/node-sea-action@v1
          with:
            working-dir: .
            output-dir: build
            executable-name: sea
            sea-config-path: test-app/sea-config.json
            node-path: /opt/hostedtoolcache/node/21.7.0/x64/bin/node
    
        - uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.os }}-sea
            path: build/
            if-no-files-found: error
